name: "generate pdf when tag"

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: "setup python"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: "install dependencies"
      run: |
        apt-get update -y && apt-get install -y git
        pip install -r requirements.txt
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: "check links"
      run: make linkcheck
    - name: "build pdf"
      run: |
        make latexpdf
        mkdir -p out
        cp ./docs/latex/SpinalHDL.pdf out/
    - name: Upload pdf
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: out/*